name: ups_service_manager
description: "UPS Service Manager - Advanced Enterprise App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_app_check: ^0.3.0

  # State
  provider: ^6.1.2

  # Local storage
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3

  # Charts
  fl_chart: ^0.68.0

  # PDF & Printing
  pdf: ^3.10.8
  printing: ^5.12.0

  # Notifications
  flutter_local_notifications: ^17.2.0

  # Connectivity
  connectivity_plus: ^6.0.3

  # UI & Animations
  shimmer: ^3.0.0
  flutter_speed_dial: ^7.0.0
  google_fonts: ^6.2.1

  # Utilities
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  share_plus: ^9.0.0
  intl: ^0.19.0
  path_provider: ^2.1.3
  uuid: ^4.4.0
  http: ^1.2.2
  crypto: ^3.0.3

  # Image display
  cached_network_image: ^3.3.1
  flutter_animate: ^4.5.2
  animations: ^2.2.0
  salomon_bottom_bar: ^3.3.2
  hive: ^2.2.3
  firebase_messaging: ^15.1.0
  signature: ^6.3.0
  excel: ^4.0.6
  geolocator: ^12.0.0
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.5
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
